# Autogenerated by matugen

# Completion widget
c.colors.completion.fg = "#e6e1e3"
c.colors.completion.bg = "#141315"
c.colors.completion.match.fg = "#cac4d5"
c.colors.completion.item.selected.fg = "#e7dff2"
c.colors.completion.item.selected.bg = "#494553"

# Statusbar
c.colors.statusbar.normal.bg = "#141315"
c.colors.statusbar.normal.fg = "#e6e1e3"
c.colors.statusbar.insert.bg = "#cac4d5"
c.colors.statusbar.insert.fg = "#322e3c"
c.colors.statusbar.passthrough.bg = "#cac4cf"
c.colors.statusbar.passthrough.fg = "#322f38"
c.colors.statusbar.command.bg = "#141315"
c.colors.statusbar.command.fg = "#e6e1e3"
c.colors.statusbar.caret.bg = "#cbc3dc"
c.colors.statusbar.caret.fg = "#322e41"
c.colors.statusbar.caret.selection.bg = "#494458"
c.colors.statusbar.caret.selection.fg = "#e7def8"
c.colors.statusbar.progress.bg = "#cac4d5"

# Tabs
c.colors.tabs.bar.bg = "#201f21"
c.colors.tabs.selected.even.bg = "#494553"
c.colors.tabs.selected.even.fg = "#e7dff2"
c.colors.tabs.selected.odd.bg = "#494553"
c.colors.tabs.selected.odd.fg = "#e7dff2"
c.colors.tabs.odd.bg = "#141315"
c.colors.tabs.odd.fg = "#e6e1e3"
c.colors.tabs.even.bg = "#141315"
c.colors.tabs.even.fg = "#e6e1e3"

# Downloads
c.colors.downloads.bar.bg = "#201f21"
c.colors.downloads.start.bg = "#cac4d5"
c.colors.downloads.start.fg = "#322e3c"
c.colors.downloads.stop.bg = "#cac4cf"
c.colors.downloads.stop.fg = "#322f38"
c.colors.downloads.error.bg = "#ffb4ab"
c.colors.downloads.error.fg = "#690005"

# Hints
c.colors.hints.bg = "#48454e"
c.colors.hints.fg = "#e6e0ec"
c.colors.hints.match.fg = "#cac4d5"

# Messages
c.colors.messages.error.bg = "#ffb4ab"
c.colors.messages.error.fg = "#690005"
c.colors.messages.info.bg = "#494553"
c.colors.messages.info.fg = "#e7dff2"
c.colors.messages.warning.bg = "#93000a"
c.colors.messages.warning.fg = "#ffdad6"

# Prompts
c.colors.prompts.bg = "#2b292b"
c.colors.prompts.fg = "#e6e1e3"
c.colors.prompts.selected.bg = "#494553"
c.colors.prompts.selected.fg = "#e7dff2"

# Webpage background
c.colors.webpage.bg = "#141315"

